spring:
  datasource:
    url: jdbc:mysql://39.108.128.19:3306/wt?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: wt
    password: xtREYw1x0bu6Jf13RTywbsv6b5fHnFjh52v4ryrqHJ13u8
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity