spring:
  datasource:
    url: jdbc:mysql://172.28.1.58:3306/dayi_wms_all?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: monda123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      pool-name: HikariPool